# Generated by Django 4.1.5 on 2023-01-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organisations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectID", models.IntegerField()),
                (
                    "projectAcronym",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("organisationID", models.IntegerField(blank=True, null=True)),
                ("vatNumber", models.IntegerField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("shortName", models.TextField(blank=True, null=True)),
                ("SME", models.CharField(blank=True, max_length=3, null=True)),
                ("activityType", models.CharField(blank=True, max_length=3, null=True)),
                ("street", models.TextField(blank=True, null=True)),
                ("postCode", models.CharField(blank=True, max_length=10, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=2, null=True)),
                ("nutsCode", models.IntegerField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=17, max_digits=20, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=17, max_digits=20, null=True
                    ),
                ),
                ("organizationURL", models.URLField()),
                ("contactForm", models.URLField()),
                ("contentUpdateDate", models.DateTimeField(blank=True, null=True)),
                ("rcn", models.IntegerField(blank=True, null=True)),
                ("order", models.IntegerField(blank=True, null=True)),
                ("role", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "ecContribution",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "netEcContribution",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "totalCost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("endOfParticipation", models.BooleanField(blank=True, null=True)),
                ("active", models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("acronym", models.CharField(blank=True, max_length=30, null=True)),
                ("status", models.CharField(blank=True, max_length=10, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("startDate", models.DateField(blank=True, null=True)),
                ("endDate", models.DateField(blank=True, null=True)),
                (
                    "totalCost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=13, null=True
                    ),
                ),
                (
                    "ecMaxContribution",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=13, null=True
                    ),
                ),
                ("legalBasis", models.CharField(blank=True, max_length=20, null=True)),
                ("topics", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "ecSignatureDate",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "frameworkProgramme",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("masterCall", models.CharField(blank=True, max_length=5, null=True)),
                ("subCall", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "fundingScheme",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("nature", models.CharField(blank=True, max_length=30, null=True)),
                ("objective", models.TextField(blank=True, null=True)),
                ("contentUpdateDate", models.DateTimeField(blank=True, null=True)),
                ("rcn", models.IntegerField(blank=True, null=True)),
                ("grantDoi", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
