# Generated by Django 4.1.5 on 2023-01-19 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EC_funding", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisations",
            name="contentUpdateDate",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 1, 19, 14, 6, 6, 785528, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
