# Generated by Django 4.1.5 on 2023-01-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EC_funding", "0002_alter_organisations_contentupdatedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisations",
            name="contentUpdateDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
