# Generated by Django 4.1.5 on 2023-01-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("EC_funding", "0003_alter_organisations_contentupdatedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisations",
            name="projectID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="EC_funding.projects"
            ),
        ),
    ]
