# Generated by Django 4.1.5 on 2023-01-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EC_funding", "0004_alter_organisations_projectid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organisations",
            old_name="projectID",
            new_name="project",
        ),
    ]
